params:
  model_name: 'SegFormer'
  batch_size: 16
  learning_rate: 0.0001
  encoder: resnet50
  augment: true
  epochs: 100
  patience: 50
  fusion_type: concat
  

data_params:
  img_size: [960, 960]
  augment: True 
  metadata_dim: 4

paths:
  dataset_base_path: 'D:/TEAM/Sneha/segmentation/\Alloy_SEM_image&mask_random_stratified_5_960'
  output_folder: 'output/SegFormer_5thset'
  
